### ISSUE TITLE
Access Denied error on moving between Extension holding dashboard to others in IE

### ISSUE THREAD

**Issue by kartheekchk86** [tableau/extension-data-driven-parameters#30]
Hi @KeshiaRose 

I noticed that there is an error coming when I move from the Dashboard which has Extension to the other dashboard. It is happening only with IE ( I am using IE 11). There is no error if I open Dashboards with out the extension directly. In Chrome I did not notice it.
Then I removed extension and tested same and no error at all. 
And the other Issue is Text Color change is also not working in IE, Showing only Black.

Could you please check it once.

![Access Denied caused by Extension v2](https://user-images.githubusercontent.com/52913211/61860055-9734f300-aec9-11e9-90a4-64f2e4f914ca.PNG)

**Comment by kartheekchk86** [comment]
Sorry. This issue is not specific to this extension. It is from Tableau directly.

**Comment by KeshiaRose** [comment]
No worries @kartheekchk86,

This was fixed a while ago so make sure to upgrade your version of Tableau Server at least to the latest maintenance release to see the issue fixed.

Take care,
Keshia

**Comment by VigneshSakkaraPandian** [comment]
Hi @KeshiaRose

I am facing the similar issue when I move from the Dashboard which has Extension to the other dashboard. I am getting the below error,
Error:
Unexpected Error
An unexpected error occurred. If you continue to receive this error please contact your Tableau Server Administrator.
Session ID: 137AFB61C5D2436C8BB7A8F292353BE5-1:1
Permission denied.
But when i was using chrome, i don't have this issue. In IE (v11)only , I am facing this issue. Then , if i removed the extension i don't have this issue in IE.
Tableau - Tableau server version is 2018.3.3
IE - Internet explorer is 11.0
Could you let me know if above the error is same as the one i was facing. if yes, can you tell me the reason for having this issue.
Please let me know which server version can I grade to resolve this issue.

**Comment by KeshiaRose** [comment]
Hi @VigneshSakkaraPandian,

This does look like the same issue that was fixed I believe around 2018.3.3 or 2018.3.4. Are you able to test your workbook on the latest version?

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Also, just in general to anyone who comes across similar issues with IE11. I would suggest stopping your use of IE11 unless absolutely necessary. It does not support modern web standards and many developers are not testing for it. I would recommend Chrome, Firefox, or Safari, or even Edge, Microsoft's modern built-in browser, which can launch IE11 for sites that need backward compatibility.

**Comment by tableau123** [comment]
Hi @KeshiaRose we are on version 2018.3.3 but still facing this issue. Also IE is the Enterprise standard in the Organization I work so can't ask users to switch to chrome. Do we need another upgrade to resolve the issue?

**Comment by KeshiaRose** [comment]
Hi @tableau123, 

I would recommend upgrading to the latest maintenance release to make sure you get the fix (also just in general). I wasn't exactly sure of the cut off date so you might not have the fix in 2018.3.3 yet. 

Take care,
Keshia

**Comment by tableau123** [comment]
Thanks. I just now noticed another issue, may be it need separate thread. I see extra whitespace around the parameter dropdown value. Its happening in Chrome but working fine in IE :)
![ParameterDropdown_IE](https://user-images.githubusercontent.com/53355482/69184812-31edb900-0adb-11ea-9d5f-6d819b828486.png)
![ParameterDropdown_Chrome](https://user-images.githubusercontent.com/53355482/69184813-32864f80-0adb-11ea-999f-746f0a991b65.png)

**Comment by tableau123** [comment]
Hi @KeshiaRose   First screenshot above is from IE and second is from Chrome. By the way, are you the same person who hosted IronViz at TC19? It was fantastic!

**Comment by KeshiaRose** [comment]
Hmmm, I have seen that a couple of times and I'm not quite sure how to fix it, but it is on my radar. We'll have to give one point to IE11 haha 😄

**Comment by KeshiaRose** [comment]
And yes that was me! Glad you enjoyed it! 😃
